
use [TestSystemDB]
--------------------------------------------------------------------------------判断题------------------------------------------------------------------------------------------------

----1. 巨量数据集合  安吉丽娜-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合'),(select top 1 ID from [TBL_TeacherInfo] where Name = '安吉丽娜'))

select * from [TBL_JudgeQuestion] where CourseID = (select top 1 ID from [TBL_CourseInfo] where CourseName ='巨量数据集合')

----2. 计算机信息管理  李思琪-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李思琪'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机信息管理')

----3. 软件技术（UI设计方向）  陈尚俊-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陈尚俊'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（UI设计方向）')

----4. 软件技术（软件外包服务方向）  肖琪琪-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）'),(select top 1 ID from [TBL_TeacherInfo] where Name = '肖琪琪'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='软件技术（软件外包服务方向）')

----5. 意识研究中的关键词题  蔡志廖-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题'),(select top 1 ID from [TBL_TeacherInfo] where Name = '蔡志廖'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='意识研究中的关键词题')

----6. 暴力行为脑机制  尚雯婕-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制'),(select top 1 ID from [TBL_TeacherInfo] where Name = '尚雯婕'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='暴力行为脑机制')

----7. 当代国际政治  吴迪迪-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吴迪迪'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='当代国际政治')

----8. 中国文化史  李丽娜-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史'),(select top 1 ID from [TBL_TeacherInfo] where Name = '李丽娜'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='中国文化史')

----9. 推理与决策  余庆柳-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策'),(select top 1 ID from [TBL_TeacherInfo] where Name = '余庆柳'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='推理与决策')

----10. 认知科学与经济学  孙剑丹-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '孙剑丹'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='认知科学与经济学')

----11. 大学经历与学生发展  苏俊力-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展'),(select top 1 ID from [TBL_TeacherInfo] where Name = '苏俊力'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='大学经历与学生发展')

----12. ACM/ICPC竞赛训练  陆志宇-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练'),(select top 1 ID from [TBL_TeacherInfo] where Name = '陆志宇'))


select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='ACM/ICPC竞赛训练')

----13. 经济学原理  王栩栩-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理'),(select top 1 ID from [TBL_TeacherInfo] where Name = '王栩栩'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='经济学原理')

----14. 计算机视觉  黄陵智-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉'),(select top 1 ID from [TBL_TeacherInfo] where Name = '黄陵智'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='计算机视觉')

----15. 发展经济学  龙丽娜-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '龙丽娜'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='发展经济学')

----16. 公共物理学  吉安娜-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '吉安娜'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='公共物理学')

----17. 量子力学  杜星宇-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学'),(select top 1 ID from [TBL_TeacherInfo] where Name = '杜星宇'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='量子力学')

----18. 地震概论  朴灿莲-------

INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService文件的扩展名是','asmx','ashx',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebService的基本通信协议是','SOAP','DCOM',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'T-SQL批处理语句块的结束标志为','GO','SUBMIT',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SQL Server 2005 是基于（）的','关系型','文件系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'“Duration=3”代表页面缓存的时间是','3秒钟','3天',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不属于用户管理控件','LoginOut','LoginName',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ASP.NET的缓存不包括','相对缓存','应用程序数据缓存',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'ORDER BY 的作用是（）','对记录排序','设置查询条件',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列不属于使用WebService的途径的是','ADO.NET','SOAP',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'( )完整性是指必须能够标识数据中的每个实体','实体','域',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'WebPartManager部件在一个ASPX页面中可以有多少个','1','2',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'下列哪些不是WebPart部件支持的模式','通讯模式','设计模式',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'(   )可以同一个表的不同字段进行联接。','自联接','内联接',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET个性化需要配置哪个配置节','Profile','MemberShip',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'使用Cookie进行身份验证的类型称为（）身份验证','forms','passport',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'SOAP的全称是','Simple Object Access Protocol','Simple Object Address process',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'判断是否为匿名用户要使用以下Profile的哪个属性','IsAnonymous','IsSynchronized',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'角色管理类Roles不能完成的功能是','重置某角色所有用户的登录密码','把用户加入角色',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'启用ASP.NET匿名个性化，需要配置哪个配置节','anonymousIdentification','compilation',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))
INSERT INTO [dbo].[TBL_JudgeQuestion] VALUES (NEWID(),'（）描述了一个用来存储数据的容器，以及该容器存储和检索数据的过程','数据模型','关系型数据库管理系统',(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论'),(select top 1 ID from [TBL_TeacherInfo] where Name = '朴灿莲'))

select * from [TBL_JudgeQuestion] where CourseID =(select top 1 ID from [TBL_CourseInfo] where CourseName ='地震概论')